print('Variables in Python')
print(False)
print('<class \'bool\'>')
print('Ini adalah tipe data boolean yang hanya memiliki dua nilai yaitu True dan False')
print(17)
print(17.11)
print('Bilangan desimal dari', 17, 'adalah', 17.11)
print([17, 11, 20, 9])
print(["tujuh belas", "sebelas", "dua puluh", "sembilan"])
print({"nama" : "Ditzzx", 'umur' : 16})